### ISSUE TITLE
Customizing css for dropdown menu

### ISSUE THREAD

**Issue by jtibbertsma** [JedWatson/react-select#1017]
I want to know how to customize the opacity of the dropdown menu. I couldn't find any documentation about customization of the css. I looked through the css file, but I couldn't find anything that has to do with the opacity of the dropdown menu. I tried setting the opacity on the `.Select-menu` and `.Select-menu-outer` classes, but that doesn't do anything.

**Comment by JasonKleban** [comment]
Setting the opacity of `.Select-menu-outer` should work.  Make sure your override is in your css AFTER the react-select css?

**Comment by muxica** [comment]
A bit late but alternately, you could simply save the react-select.css file locally and edit it there. This way you don't have to render the original styles then render the overrides. The link to the most recent, as of this post, css file. If you're using a previous version, just replace the version number in the link between @ and /dist/react-select.css
https://npmcdn.com/react-select@1.0.0-beta13/dist/react-select.css

**Comment by jtibbertsma** [comment]
See, the weird thing is that if you look at the css file, you won't find any opacity value that isn't 1 or 0. That's what confused me originally. Take a look:
```css
.Select-menu-outer {
  border-bottom-right-radius: 4px;
  border-bottom-left-radius: 4px;
  background-color: #fff;
  border: 1px solid #ccc;
  border-top-color: #e6e6e6;
  box-shadow: 0 1px 0 rgba(0, 0, 0, 0.06);
  box-sizing: border-box;
  margin-top: -1px;
  max-height: 200px;
  position: absolute;
  top: 100%;
  width: 100%;
  z-index: 1;
  -webkit-overflow-scrolling: touch;
}
.Select-menu {
  max-height: 198px;
  overflow-y: auto;
}
```

**Comment by jtibbertsma** [comment]
Oh I see! They're setting it in the box-shadow property. Problem solved.

**Comment by jtibbertsma** [comment]
Um, no. You can't set opacity with the box-shadow property. I was half asleep when I wrote that. Anyway, the css above doesn't have any opacity property set, but the opacity looks to be around 0.6. Setting it in .Select-menu-outer doesn't work, and I'm positive that I'm setting after the react-select css. Here's what I've got in my scss file:
```css
@import '../../node_modules/react-select/scss/default';

.Select-control {
  border-radius: 20px;
}

.Select-menu-outer {
  font-weight: 500;
  border-bottom-right-radius: 20px;
  border-bottom-left-radius: 20px;
  opacity: 0.9;
}

.Select-menu {
  border-bottom-right-radius: 20px;
  border-bottom-left-radius: 20px;
}

.Select-option {
  color: #222;
}

.Select-option.is-focused {
  color: white;
  background: #7E96C8;
}
```
The other styles I'm setting are showing up.
