### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by kathgironpe** [JedWatson/react-select#1093]
I am not certain if anyone encountered this with their project. 

I do not use frameworks like Bootstrap. 

I get some issues with the form field input. It appears smaller than it should be when users start typing. 

Here's my fix:

``` css
.Select-input {
  padding: 0 !important;
}

.Select-input,
.Select-input input {
  width: 100% !important;
}

.Select-input input {
  text-indent: 10px;
}
```
