### ISSUE TITLE
Multiple style variations

### ISSUE THREAD

**Issue by burtyish** [JedWatson/react-select#1144]
We've adopted react-select as our default select component since I've had good experience with it in the past.
Our new project has several types of select components, each styled differently and they may be used on the same page.

Type 1: <img width="76" alt="screen shot 2016-08-04 at 10 17 52" src="https://cloud.githubusercontent.com/assets/4200728/17394355/59192ce8-5a31-11e6-8930-29954a8ecd14.png">
Type 2: <img width="135" alt="screen shot 2016-08-04 at 10 17 45" src="https://cloud.githubusercontent.com/assets/4200728/17394364/63dc1fa0-5a31-11e6-8e27-44a5359e0dad.png">

Since react-select uses scss `!default`, it's easy to override the text color by defining a new value for`$select-text-color`.

However, if I want two different variation types of styles for `.Select-value-label`, things get complicated and fragile. I cannot simply override the original value with another value, since each type needs a different style.

Here's the original scss. Note that it is highly specific:

``` scss
.has-value.Select--single > .Select-control .Select-value,
.has-value.is-pseudo-focused.Select--single > .Select-control .Select-value {
    .Select-value-label {
        color: $select-text-color;
    }
}
```

So, in order to override it for `.Select--type-1` and `.Select--type-2`, I'm _forced_ to write these two rules:

``` scss
.Select--type-1 {
    &.has-value.Select--single > .Select-control .Select-value,
    &.has-value.is-pseudo-focused.Select--single > .Select-control .Select-value {
        .Select-value-label {
            color: $select-text-color-type-1;
        }
    }
}
.Select--type-2 {
    &.has-value.Select--single > .Select-control .Select-value,
    &.has-value.is-pseudo-focused.Select--single > .Select-control .Select-value {
        .Select-value-label {
            color: $select-text-color-type-2;
        }
    }
}
```
1. I see the css here follows BEM and these selectors do seem highly nested and specific to me, a practice discouraged in BEM.
2. A concern has been raised here that the new selectors we'll write may be broken by future changes in the structure..
   So is there any part of these selectors that's unnecessary? Can we cut down on the specificity? 

Alternatively, is there a better way of getting multiple types of customized styles?

Thanks!
