### ISSUE TITLE
Wrong input size in Firefox

### ISSUE THREAD

**Issue by krom** [JedWatson/react-select#1282]
http://jedwatson.github.io/react-select/ in firefox
![Alt text](https://monosnap.com/file/tMYuMebyT3YdQyKK4bd5tdTgetnCoC.png)

Fixed temporary with css:

``` css
.Select-input > input {
    height: 16px;
}
```

_Firefox 49.0.1 at masOS_
