### ISSUE TITLE
Remove Options Drop-Down

### ISSUE THREAD

**Issue by emorling** [JedWatson/react-select#1546]
Is it possible to remove the drop-down for creatable? So it simply works like an input box for tags, without a select?

**Comment by avinmathew** [comment]
You can hide it via CSS:
```css
.hide-options .Select-arrow-zone {
    display: none;
}

.hide-options .Select-menu-outer {
    display: none;
}
```

```jsx
<Creatable
    className="hide-options"
/>
```
