### ISSUE TITLE
Increasing font-size almost works...

### ISSUE THREAD

**Issue by super-cache-money** [JedWatson/react-select#1925]
The following is using 1.0.0-rc.5:

Here is how it looks with the default font size:
![image](https://user-images.githubusercontent.com/1463145/29244193-5d6fe712-7fb2-11e7-9ada-a30ddf4db3af.png)

Then, if the font-size of `.Select` is set to 20px, it kinda works:
![image](https://user-images.githubusercontent.com/1463145/29244181-311398da-7fb2-11e7-8038-f194d2dd767b.png)

But, if you set the font size to say, 30px, all bets are off:
![image](https://user-images.githubusercontent.com/1463145/29244188-50df0776-7fb2-11e7-888d-5ede45a8adaa.png)

"Queensland" seems like it's got a bottom-margin that's too high or something. The same thing happens to the placeholder.

It'd be great if this worked...

**Comment by mDibyo** [comment]
To make this work for font size 70px, I had to add these styles:
```css
.Select-control {
    height: 70px;
}


.Select-placeholder, .Select--single > .Select-control .Select-value {
    line-height: 70px;
}

.Select-clear {
    font-size: inherit;
}

.Select-arrow-zone {
    padding: 0 15px;
}

.Select-arrow {
    top: 5px;
    border-width: 15px 15px 10px;
}

.is-open > .Select-control .Select-arrow {
    top: 0;
    border-width: 0 15px 15px;
}

.Select-menu-outer, .Select-menu {
    max-height: none;
}
```
