### ISSUE TITLE
On Select Faint Blue Outline (CSS Issue)

### ISSUE THREAD

**Issue by jamesfriedal** [JedWatson/react-select#2061]
After an input is selected a faint blue 2px (estimated) outline appears around the input box. 
It is there on all the examples. (You have to select an input first and then it goes away on click)

The only two css properties I thought could be causing this are outline / border so I've tried the following in CSS but to no avail.

```
*
  outline: none !important
  border: none !important
```

Does anyone now how to get rid of this faint light blue background. 
Thanks

**Comment by nikklassen** [comment]
I believe what you're seeing is the style defined [here](https://github.com/JedWatson/react-select/blob/a1e1069d2fa02cfeb47401ae57b096606ea17ca9/scss/control.scss#L61). You can override it with the selector `.Select.is-focused:not(.is-open) > .Select-control`, for example.

**Comment by Hongbo-Miao** [comment]
Same here. Even tried

```css
* {
  outline: 0 !important;
  border: 0 !important;
}
```

```css
* {
  outline: none !important;
  border: none !important;
}
```
but neither works.

like below
![image](https://user-images.githubusercontent.com/3375461/31872372-518ba3c8-b770-11e7-80e9-c71818bc001f.png)
