### ISSUE TITLE
ios/safari: when zoomed on dropdown i can no longer scroll up or down.

### ISSUE THREAD

**Issue by JochemWarmenhoven** [JedWatson/react-select#2065]
I also tested it on the example site: http://jedwatson.github.io/react-select/.
I would like to know if there is a known solution

**Comment by martgnz** [comment]
If you are referring to the zoom iOS does sometimes when opening the dropdown, I was able to disable it by setting the `input` font size to `16px`.

Something like this:

```css
@media (max-width: 500px) {
  .Select input {
    font-size: 16px;
  }
}
```
