### ISSUE TITLE
Support inline-block / sizes

### ISSUE THREAD

**Issue by dantman** [JedWatson/react-select#323]
react-select only seems to work as a full-width block component. It would be nice if it would also support use as an inline-block component (like a standard `<select>`) with either an auto-calculated width or a specified width.

**Comment by danilotorrisi** [comment]
+1

**Comment by mik01aj** [comment]
@dantman can't you just put the `Select` inside an `inline-block`?

**Comment by dantman** [comment]
> @dantman can't you just put the Select inside an inline-block?

That is what I'm doing now. But A) it should not be necessary and B) automatic sizing (like how normal selects work) cannot be done that way.

**Comment by alesn** [comment]
Is there a way to make react-select be auto-sized (by content size) and not take up the full width of its parent (or having to be sized to a fixed width that would have to be calculated somehow from the content)?

**Comment by JedWatson** [comment]
ping @jossmac

**Comment by jossmac** [comment]
I was going to say wrap it, but that's been covered by @mik01aj 

@dantman could you please provide a use case, preferably with screenshots?

If we're going to support this let's discuss how it's expected to work:
- regarding width
  - set explicitly
  - length of the current value
  - length of the longest option
- would it collapse without a value?
- what is expected when the `multi` property is `true`?

**Comment by alesn** [comment]
I've created a jsfiddle demonstrating different use cases
https://jsfiddle.net/Lp51Ldu8/1/
I included notes directly in the fiddle. Defining a fixed width would be ok e.g. for measurements units but for localized names of levels (different length in different languages), it would not be the best solution.

In simple terms, I would need a react select component that can behave the same as the standard html select input control in terms of being an inline element sized by its content width. Even just react-select component having the width - both when open and closed - as the longest option, would be sufficient for me

**Comment by bcardiff** [comment]
+1

**Comment by freder** [comment]
+1

**Comment by tonybaroneee** [comment]
+1

**Comment by gsdean** [comment]
+1

**Comment by jossmac** [comment]
Update: the reason we haven't gone ahead with this feature is two fold;

1. To get the desired width of the component we would have to loop through each of the children finding the option with the greatest character length, which would decrease performance
2. After arriving at this number we'll have to add some fuzzy logic by getting the current font-size and multiplying from there to arrive at the width. This could go horribly wrong in a few cases

If using a fixed-width works for your application, I recommend the wrapping the react-select component with your own and handling the `inline-block` and `max-width` declarations inside of it. Something like this:
```jsx
displayName: 'MySelect',
render () {
  return (
    <div style={{ display: 'inline-block', maxWidth: this.props.maxWidth }}>
      <ReactSelect {...this.props} />
    </div>
  )
}
```
```jsx
<MySelect ... />
```
_ping_ @JedWatson safe to close?

**Comment by tonybaroneee** [comment]
Hey @jossmac, it's actually way less complicating than that. It basically involves changing `.Select-control` to `width: auto` and having the `.Select-value` not be absolutely-positioned (plus a few other css cleanups).

**Comment by jossmac** [comment]
@tonybaroneee sounds good man, would you mind submitting a PR?

**Comment by tonybaroneee** [comment]
Sure, I'll try to get to it soon.

**Comment by Nyalab** [comment]
that would be pretty useful, can't wait to see the PR :+1:

**Comment by cedricdelpoux** [comment]
Hey, I really need this feature. I tried to change what you said @tonybaroneee but it was not as simple as you said because we need to handle the search feature and the multi feature. So I hope you found the solution :)

**Comment by brutcha** [comment]
+1

**Comment by jossmac** [comment]
@tonybaroneee any word on that PR?

**Comment by tonybaroneee** [comment]
Sorry for the delay, been super busy. I'm home on break now, so will try to
work on it this week!

**Comment by tonybaroneee** [comment]
@cedricdelpoux you're right, this is turning out to be quite a bear based on the combination of elements within a `.Select` at any given time :stuck_out_tongue:

**Comment by axelson** [comment]
Is it possible to get @jossmac's [solution](https://github.com/JedWatson/react-select/issues/323#issuecomment-161522621) added to the docs? Or added as an example?

**Comment by luckygerbils** [comment]
Hey, I have a working solution (not fit to be merged at the moment) in my branch [here](https://github.com/luckygerbils/react-select/tree/inline-block-0.9.1). Live example [here](http://luckygerbils.github.io/react-select/).

Basically I've made it so the collapsed menu isn't actually removed, it just renders with 0 height. This lets us measure the width and keep it in sync with the width of the main element.

There's obviously a lot more changes that need to be made before this can be merged (such as a prop to turn this on or off), but I'd love some feedback on whether or not people think this is a viable route to go.

**Comment by fay-jai** [comment]
I just tried @jossmac 's solution and unfortunately, it doesn't seem to be working for me - anyone else got it to work and can provide a working example?

**Comment by fay-jai** [comment]
I couldn't get @jossmac 's solution to work, but this worked for me:

```css
.Select-input > input {
    max-width: X - 50px; // where X is the max width that you want
}
```

**Comment by shanSyapse** [comment]
To dynamically adjust the height as user pick from the options, I spent a full day using js ways to dynamically adjust the Select width based on the option length.
Then a CS ninja showed me this that works like crazy:
```
.Select-input {
     position: absolute;
}
.Select-value-label {
	display: block;
}
.Select-value {
	position: relative;
	white-space: normal;
}
```

**Comment by nevaenuf** [comment]
Will this be implemented in the 1.0 version?

**Comment by ryan4888** [comment]
+1

**Comment by JedWatson** [comment]
Everyone who's +1'd this, @jossmac and I think we might be able to implement this, but can you tell us more about the use-case please? we're not convinced this isn't easier to handle with a wrapper around react-select, and continue to have the control take up 100% of the _available_ space by default.

**Comment by alexeyOnGitHub** [comment]
my use-case is: show several elements in the same row:
`<field_name>:  <react-select-component-here>   <field_value>`

e.g. 

`Parameter1   <Select: "equals, not equal, contains, etc">    Text Edit box for Parameter1 value here`

**Comment by brutcha** [comment]
@alexeyOnGitHub we have exactly same usecase in our app. I have written some css, which is not ready for all uses of a component (for example we don't use prop clearable=true). There is some custom styles also (padding of loading zone).

It's works nice in a row, but is not exactly a inline/block usage (options will overflow selected value when are wider).

This is our "condensed" stylesheet
```css
.Select-container.condensed .Select .Select-control {
    width: auto;
}
.Select-container.condensed:not(.multi) .Select .Select-value,
.Select-container.condensed .Select .Select-placeholder {
    position: static;
    display: table-cell;
    padding-right: 0;
}
.Select-container.condensed .Select .Select-loading-zone {
    padding-left: 5px
}
.Select-container.condensed:not(.multi) .Select .Select-value ~ .Select-input,
.Select-container.condensed .Select .Select-placeholder ~ .Select-input {
    position: absolute;
    left: 0;
}
.Select-container.condensed .Select .Select-menu-outer {
    width: auto;
    min-width: 100%;
}
.Select-container.condensed .Select .Select-menu {
    overflow-y: auto;
    overflow-x: hidden;
}
.Select-container.condensed:not(.multi) .Select .Select-option {
    white-space: nowrap;
    padding-right: 25px; /* absolute positioning scrollbar fix */
}
.Select-container.condensed.multi .Select .Select-multi-value-wrapper {
    display: initial;
    position: initial;
}
```
