### ISSUE TITLE
Dark theme for documentation

### ISSUE THREAD

**Issue by vitaly-zdanevich** [JedWatson/react-select#4067]
Please do not ignore [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

**Comment by StarNeit** [comment]
How can we easily implement the dark theme for `react-select`?
If there is any solution or documentation, that would be great.
@vitaly-zdanevich , @bladey

**Comment by vitaly-zdanevich** [comment]
On this link from original post https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme, for example:

```
@media (prefers-color-scheme: dark) {
    .myclass { background: black, color: gray }
}

@media (prefers-color-scheme: light) {
    .myclass { background: white, color: darkgray }
}
```

**Comment by ebonow** [comment]
Greetings @vitaly-zdanevich and sorry for the long wait for a reply. 

Applied this to the body and it's certainly a start.
<img width="800" alt="Screen Shot 2021-01-17 at 7 17 31 PM" src="https://user-images.githubusercontent.com/1007579/104868852-5ae52600-58f9-11eb-90a0-d63bb5c94124.png">

My question for this would be the expectation of a dark theme for react-select itself as its presented throughout the documentation. On one hand, it would fit the documentation better, but on another, it could potentially add complexity to all of the code examples for the sake of documentation aesthetics.

@bladey would you be able to inquire a bit more internally about any existing atlaskit dark themes? I'm curious if something like this already exists. 

Otherwise @Jeffshek shared his dark theme in an open thread here: https://github.com/JedWatson/react-select/issues/3692#issuecomment-671084399 that can be applied to react-select

**Comment by ebonow** [comment]
For those of you using stylish, here's the applied stylesheet I'm using:

`Applies to URLS on the domain: react-select.com`

```css
@media(prefers-color-scheme: dark) {
    body {
        background: black;
		color: gray;
    }
    h1, h2, h3, h4 {
    	color: #999;
    }

    pre {
        padding: .5rem !important;
        background: #333 !important;
    }

    code {
        color: #ccc !important;
        background: #333 !important;
    }

    pre span { 
        background: inherit !important;
    }

    [role=button] {
        box-shadow: inset 0 0 2rem rgba(33, 33, 33, .3);
        padding-left: .5rem;
        margin-left: -2rem;
    }
}
```
