### ISSUE TITLE
setting height of select box

### ISSUE THREAD

**Issue by mahsashadi** [JedWatson/react-select#4285]
hello, sorry for asking question here

what is the right way for setting select box **height**?
I need to change both `control` and `valueContainer` to see changing in heigh, as below:
```
 control: (provided, state) => ({
   ...provided,
   height:'40px'
 }),
  valueContainer: (provided, state) => ({
    ...provided,
    height:'40px'
 }),
```
But it causes the value in selectbox moves up as I  click inside
![Screenshot from 2020-11-17 16-43-56](https://user-images.githubusercontent.com/70196035/99394497-38805d80-28f4-11eb-99e9-293de5ba3a7d.png)

**Comment by ebonow** [comment]
Greetings @mahsashadi ,

I am not able to replicate the styling you are seeing. Based on the screenshot, there might be some compatibility issues with some of the styling you are seeing. 

The SingleValue is positioned absolutely and vertically with     
```
  top: 50%;
  -webkit-transform: translateY(-50%);
  -ms-transform: translateY(-50%);
  transform: translateY(-50%);
```

So it could be some browser/OS compatibility with that. 

Perhaps try another method of vertically positioning the SingleValue (would also need to be done for MultiValueContainer for isMulti).

```
const styles = {
   ...
  singleValue = (provided, state) => ({
    top: 0,
    transform: 'none',
    line-height: '40px',
  })
};
```

Hope this helps and let me know if it doesn't.

**Comment by mahsashadi** [comment]
Hi, Thank you for you reply.
I understand that the problem was about `valueContainer`, not `singleValue`

To match with the chosen height of `control` component, I need to add these styles:
```css
.react-select__value-container{
  top: '50%';
  transform: 'translateY(-50%)'
 }

.react-select__indicators{
  position: absolute;
  top: '50%';
  transform: 'translateY(-50%)';
  right:0; 
 }
```
