### ISSUE TITLE
Axe is reporting 'Elements must have sufficient color contrast' for input

### ISSUE THREAD

**Issue by Kretajak** [JedWatson/react-select#4814]
Axe is reporting `Elements must have sufficient color contrast` with comment: `Element's background color could not be determined because it is overlapped by another element`. 

This is because `<input>` element is covered by `placeholder` element thus not letting axe to calculate contrast. This can block axe from catching violations like a too low contrast.

**Steps to reproduce:**

* Enter page: https://798fh.csb.app/
* Run axe check

**Workaround**:

Use custom CSS that will render input in front of absolutely positioned placeholder: 

```scss
div.placeholder {
  & + div {
    position: relative;

    input {
        cursor: pointer;
    }
  }
}
```
