### ISSUE TITLE
Strange White Box appears on iOS Mobile Browser

### ISSUE THREAD

**Issue by TheMrFrick** [JedWatson/react-select#5946]
## Random White Box Bug

react-select version: ^v.5.7.0

On our mobile site for iOS, we have an odd case where users are experiencing a white box appear when they open up and close a react-select dropdown.

Video of the issue submitted by one of our users:

https://github.com/user-attachments/assets/4103892f-5d51-49a6-b6c2-e30d2691d6b4

Here are our CSS styles that we are adding on top of the React-Select object. 

```css
.React_Select__control {
    background-color: ${({ theme }) => theme.colors.inputs.text.background};
    border-color: ${({ theme }) => theme.colors.inputs.text.border};
    outline: none !important;
    &:hover,
    &:focus {
      border-color: ${({ theme }) => theme.colors.second};
    }
  }
  .React_Select__multi-value {
    background-color: ${({ theme }) => theme.colors.main};
    border: 1px solid;
    border-color: ${({ theme }) => theme.colors.inputs.text.border};
    min-width: 80px;
    display: flex;
    justify-content: space-between;
    border-radius: 5px;
  }
  .React_Select__multi-value__label {
    color: white;
  }
  .React_Select__single-value {
    color: ${({ theme }) => theme.colors.inputs.text.textColor};
  }

  .React_Select__multi-value__remove {
    color: crimson;
    border: none;

    &:hover {
      color: white;
      background-color: crimson;
    }
  }
  .React_Select__menu {
    background-color: ${({ theme }) => theme.colors.inputs.text.background};
    border-color: ${({ theme }) => theme.colors.inputs.text.border};
    border: 1px solid;
    z-index: 1000;
  }
  .React_Select__option {
    background-color: ${({ theme }) => theme.colors.inputs.text.background};
    color: ${({ theme }) => theme.colors.inputs.text.textColor};
    &--is-focused {
      background-color: ${({ theme }) => theme.colors.second};
      color: white;
    }
  }
  .React_Select__input {
    input {
      color: ${({ theme }) => theme.colors.inputs.text.textColor} !important;
    }
  }
```
