### ISSUE TITLE
Height of dropdow

### ISSUE THREAD

**Issue by igorapa** [JedWatson/react-select#704]
Hey folks, 

I'm trying to control the height of the dropdown, I'd like to use a small dropdown.
I found on README this `menuBuffer`, but din't work.

I solved this with CSS, see:

``` css
.Select-menu-outer * {
  max-height: 95px;
}
```

I know, this is a mistake.
Please, any idea?

Tks
