### ISSUE TITLE
Semantic UI compatibility

### ISSUE THREAD

**Issue by bkniffler** [JedWatson/react-select#742]
Hey, 
Love react-select, but there is one thing bothering me, its style conflicts with the popular semantic-ui library. 

This is the style that gets applied to Select > Select-control > Select-input > input, as it gets selected by `input:not([type])`

``` css
.ui.form input:not([type]), .ui.form input[type=text], .ui.form input[type=email], .ui.form input[type=search], .ui.form input[type=password], .ui.form input[type=date], .ui.form input[type=datetime-local], .ui.form input[type=tel], .ui.form input[type=time], .ui.form input[type=url], .ui.form input[type=number] {
    font-family: Lato,'Helvetica Neue',Arial,Helvetica,sans-serif;
    margin: 0;
    outline: 0;
    -webkit-appearance: none;
    tap-highlight-color: rgba(255,255,255,0);
    line-height: 1.2142em;
    padding: .67861429em 1em;
    font-size: 1em;
    background: #FFF;
    border: 1px solid rgba(34,36,38,.15);
    color: rgba(0,0,0,.87);
    border-radius: .28571429rem;
    box-shadow: 0 0 0 0 transparent inset;
    -webkit-transition: color .1s ease,border-color .1s ease;
    transition: color .1s ease,border-color .1s ease;
}
```

A possible, easy solution would be to give the `<input />` a type attribute like `<input type="react-select"/>`.
