### ISSUE TITLE
Select arrow is not flipping when the menu is open

### ISSUE THREAD

**Issue by ypt** [JedWatson/react-select#789]
The nesting of of the `.Select-arrow` element must have changed at some point so that `.is-open > .Select-control > .Select-arrow` no longer selects the element.

SCSS selector:

https://github.com/JedWatson/react-select/blob/e60c6f4097a8c2cef96cdfec881a6088e3dcdbdf/scss/control.scss#L67

Element nesting:
<img width="802" alt="screen shot 2016-02-24 at 4 56 06 pm" src="https://cloud.githubusercontent.com/assets/2073178/13302389/a59e6f9a-db17-11e5-88ac-3ab7b0ffdbcb.png">

I think the fix is to change 

``` css
.is-open > .Select-control > .Select-arrow
```

 to 

``` css
.is-open > .Select-control .Select-arrow
```

If this looks ok, I can submit a PR.

**Comment by hbarudin** [comment]
+1 - having the same issue. @ypt can you show more about how you were able to fix?

**Comment by akrikos** [comment]
I'm using a similar fix. I also found that I didn't like that the arrow appears to not just flip, but actually move down just due to how it was implemented. So I pull it up 2px when it's flipped:
```less
.is-open > .Select-control .Select-arrow {
  position: relative;
  top: -2px;
  border-color: transparent transparent @select-arrow-color;
  border-width: 0 @select-arrow-width @select-arrow-width;
}
```
