### ISSUE TITLE
css border-color is ignored

### ISSUE THREAD

**Issue by FourwingsY** [JedWatson/react-select#880]
in `.Select-control`,
border options are set as

``` scss
.Select-control {
    border-color: lighten($select-input-border-color, 5%) $select-input-border-color darken($select-input-border-color, 10%);
    border-radius: $select-input-border-radius;
    border: $select-input-border-width solid $select-input-border-color;
}
```

while `border-color` is faster than `border`, border color properties will be ignored.
